#!/bin/bash
#author:suquan 240129745@qq.com
#version:v1.0
#install
if [  ! -e "/bin/dict" ]
then
	sudo cp $PWD/dict /bin/dict
fi
if [[ $# -lt 1 ]]
then
	echo "Usage: $0 word"
	exit 1
fi

url=www.dict.cn
which lynx >/dev/null
if [[ $? -ne 0 ]]
then
	echo "sorry,can not found the lynx,pls install it!!!"
	exit 1
fi
dictfile=/tmp/dict-$1-$$
lynx -dump $url/$1 |sed 's/\#\[1\]alternate//'|sed '/^$/d'|awk '!/http:/'|tr -s "\n"|tee $dictfile|less
#over
